project:
  type: book

book:
  title: "IEB - Syllabus"
  author: "Miguel Utrilla"
  date: "30/6/2023"
   chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt

editor: visual

